# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_web_secret]
# 平台端的密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
api_allow_origins = [] # API 服务允许 CORS 的源列表。
jwt_secret = "<Replace me with str value>" # 内置 API 的身份认证密钥，用于签名和验证有效性。

[bot_web]
# 平台端的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
login_max_attempts = 5 # 登录请求最大次数限制。
enable = true # 是否启用此平台。
api_port = 5000 # API 服务的端口号，设为 0 则禁用 API 服务。
webui_host = "127.0.0.1" # WebUI 服务的主机地址，设为 0.0.0.0 则监听所有地址。
webui_port = 8081 # WebUI 服务的端口号，设为 0 则禁用 WebUI 服务。
